export default [
    {
        type: "number",
        label: "DISK STORAGE (MB)",
        min: "8192",
        max: "200480",
        step: "1024",
        name: "storage",
        id: "storage",
        placeholder: "ENTER THE DISK STORAGE (min : 8192 in MB)",
    },
    {
        type: "number",
        label: "CORE",
        min: "2",
        max: "8",
        step: "2",
        name: "core",
        id: "core",
        placeholder: "ENTER THE NUMBER OF CORE",
    },
    {
        type: "number",
        label: "CORE FREQUENCY",
        min: "1",
        max: "6",
        step: "1",
        name: "coreFrenquency",
        id: "coreFrenquency",
        placeholder: "ENTER THE FRENQUENCY OF CORE",
    },
    {
        type: "number",
        label: "IPV",
        min: "4",
        max: "6",
        step: "2",
        name: "IPV",
        id: "IPV",
        placeholder: "ENTER THE IPV(4/6)",
    },
    {
        type: "number",
        label: "RAM",
        min: "2",
        max: "16",
        step: "2",
        name: "RAM",
        id: "RAM",
        placeholder: "ENTER THE NUMBER OF RAM",
    },
    {
        type: "number",
        label: "MEMORY SIZE(MB)",
        min: "2048",
        max:"8192",
        step: "1024",
        name: "RAM",
        id: "RAM",
        placeholder: "ENTER THE MEMORY SIZE(min : 2048  in MB)",
    },
    {
        type: "number",
        label: "BANDWIDTH",
        min: "10",
        max: "100",
        step: "10",
        name: "cpu",
        id: "cpu",
        placeholder: "ENTER THE BANDWIDTH ( min 10 to 100)",
    },
    {
        type: "number",
        label: "VERSION",
        min: "10.0",
        max: "10.9",
        step: "0.1",
        name: "version",
        id: "version",
        placeholder: "ENTER THE VERSION",
    }
];